# Generated by Django 4.2.3 on 2023-07-22 11:10

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_image_options_alter_place_description_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(max_length=10000, verbose_name='Полное описание'),
        ),
    ]
